config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/destroy', to: 'auth#destroy', as: :sign_out

    resources :bulletins do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    scope module: :profile do
      get 'profile', to: 'bulletins#index'
    end

    namespace :admin do
      root 'bulletins#under_moderation'

      resources :categories, except: :show

      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :archive
          patch :reject
        end
      end
    end
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  belongs_to :category
  belongs_to :user

  has_one_attached :image

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 1000 }
  validates :image,
            attached: true,
            content_type: ['image/png', 'image/jpeg'],
            size: { less_than: 5.megabytes }

  aasm column: :state, whiny_transitions: false do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :to_moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :archive do
      transitions from: %i[published under_moderation rejected draft], to: :archived
    end
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[title state category_id]
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

class Web::Admin::BulletinsController < Web::Admin::ApplicationController
  before_action :set_bulletin, except: %i[index under_moderation]

  def index
    @q = Bulletin.ransack(params[:q])
    @bulletins = @q.result.includes(:category, :user).order(created_at: :desc).page(params[:page])
    authorize [:admin, @bulletins]
  end

  def under_moderation
    @bulletins = Bulletin.under_moderation.includes(:category, :user).order(created_at: :desc).page(params[:page])
    authorize [:admin, @bulletins]
  end

  def destroy
    @bulletin.destroy!
    redirect_to admin_bulletins_path, notice: t('.destroyed')
  end

  def publish
    if @bulletin.may_publish?
      @bulletin.publish!

      redirect_to admin_root_path, notice: t('.success')
    else
      redirect_to admin_root_path, notice: t('failure')
    end
  end

  def reject
    if @bulletin.may_reject?
      @bulletin.reject!

      redirect_to admin_root_path, notice: t('.success')
    else
      redirect_to admin_root_path, notice: t('failure')
    end
  end

  def archive
    if @bulletin.may_archive?
      @bulletin.archive!

      redirect_back(fallback_location: admin_bulletins_path, notice: t('.success'))
    else
      redirect_back(fallback_location: admin_bulletins_path, notice: t('failure'))
    end
  end

  private

  def set_bulletin
    @bulletin = Bulletin.find(params[:id])
    authorize [:admin, @bulletin]
  end

  def bulletins_params
    params.require(:bulletin).permit(:title, :description, :user_id, :category_id, :image)
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

class Web::BulletinsController < Web::ApplicationController
  before_action :set_bulletin, except: %i[index new create]

  def index
    @q = Bulletin.published.ransack(params[:q])
    @bulletins = @q.result.includes(:category, :user).order(created_at: :desc).page(params[:page])
    authorize @bulletins
  end

  def show; end

  def new
    @bulletin = Bulletin.new
    authorize @bulletin
  end

  def edit; end

  def create
    @bulletin = current_user.bulletins.build(bulletins_params) if current_user
    authorize Bulletin

    if @bulletin.save
      redirect_to @bulletin, notice: t('success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bulletin.update(bulletins_params)
      redirect_to profile_path, notice: t('success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def to_moderate
    if @bulletin.may_to_moderate?
      @bulletin.to_moderate!

      redirect_to profile_path, notice: t('.success')
    else
      redirect_to profile_path, alert: t('failure')
    end
  end

  def archive
    if @bulletin.may_archive?
      @bulletin.archive!

      redirect_to profile_path, notice: t('.success')
    else
      redirect_to profile_path, alert: t('failure')
    end
  end

  private

  def set_bulletin
    @bulletin = Bulletin.find(params[:id])
    authorize @bulletin
  end

  def bulletins_params
    params.require(:bulletin).permit(:title, :description, :user_id, :category_id, :image)
  end
end

app/controllers/web/profile/application_controller.rb
# frozen_string_literal: true

class Web::Profile::ApplicationController < Web::ApplicationController
end

app/controllers/web/profile/bulletins_controller.rb
# frozen_string_literal: true

class Web::Profile::BulletinsController < Web::Profile::ApplicationController
  def index
    raise Pundit::NotAuthorizedError unless current_user

    @q = current_user.bulletins.ransack(params[:q])
    @bulletins = @q.result.page(params[:page])
  end
end

app/views/web/profile/bulletins/index.html.slim
= content_for :title do
  = t('.title')

= link_to t('.new'), new_bulletin_path, class: 'btn btn-outline-primary mb-4'

- collection = Bulletin.aasm.states.map(&:name).map { |state| [t("web.bulletins.states.#{state.name}"), state.name] }

= render 'web/search_form',
          q: @q,
          url: profile_path,
          cont: :title_cont,
          eq: :state_eq,
          collection: collection,
          placeholder: t('simple_form.ransack.placeholders.title'),
          prompt: t('simple_form.ransack.prompts.state')

table.table.mb-5
  thead
    tr
      th{ scope = 'col' } = t('.cols.title')
      th{ scope = 'col' } = t('.cols.state')
      th{ scope = 'col' } = t('.cols.created_at')
      th{ scope = 'col' } = t('.cols.actions')

  tbody
    - @bulletins.each do |bulletin|
      tr
        td = bulletin.title
        td = t(".states.#{bulletin.state}")
        td = bulletin.created_at.strftime('%d.%m.%Y, %H:%M')

        td.d-flex
          = link_to t('show'), bulletin, class: 'me-4'
          = link_to t('edit'), edit_bulletin_path(bulletin), class: 'me-4'
          - if bulletin.draft?
            = link_to t('to_moderate'), to_moderate_bulletin_path(bulletin),
              class: 'me-4', data: { turbo_method: :patch, turbo_confirm: t('confirmation') }
          - unless bulletin.archived?
            = link_to t('archive'), archive_bulletin_path(bulletin),
              class: 'link-danger me-4', data: { turbo_method: :patch, turbo_confirm: t('confirmation') }

.d-flex.justify-content-center.mt-3
  = paginate @bulletins