config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/destroy', to: 'auth#destroy', as: :sign_out

    resources :bulletins do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    scope module: :profile do
      get 'profile', to: 'bulletins#index'
    end

    namespace :admin do
      root 'bulletins#under_moderation'

      resources :categories, except: :show

      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :archive
          patch :reject
        end
      end
    end
  end
end

app/views/layouts/web/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.to_hash.each_value do |msg|
      .alert.alert-info
        = msg

app/views/layouts/web/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to t('.title'), root_path, class: 'navbar-brand me-md-4'

      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          - if signed_in?
            li.nav-item.me-4
              = link_to t('.profile'), profile_path, class: 'nav-link link-dark'
            li.nav-item.me-4
              = link_to t('.create_bulletin'), new_bulletin_path, class: 'nav-link link-dark'

    ul.nav.nav-pills
      - if current_user&.admin?
        li.nav-item.me-2
          = link_to t('.admin'), admin_root_path, class: 'nav-link link-dark'
      - if signed_in?
        li.nav-item.me-2
          = link_to t('.sign_out'), sign_out_path, data: { turbo_method: :delete }, class: 'nav-link link-dark'
      - else
        = button_to t('.sign_in'),
                  auth_request_path(:github),
                  data: { turbo: false },
                  method: :post,
                  class: 'nav-link link-dark'